---

#Deploy
- name: Deploy API
  hosts: "api_legacy_test"
  gather_facts: True
  roles:
    - role: common
      become: true
    - role: cerftbot
      become: true
    - role: api-legacy
      become: true