---

- name: Create the config file directory
  file: path={{ config_directory_path }}
    mode=0775
    state=directory

- name: Copy the env file
  template: src=env.j2 dest={{ config_directory_path }}/env.ini

- name: Copy the gCloud credentials file
  template: src=gcloud.json.j2 dest={{ config_directory_path }}/gcp.json

- name: Run api
  become: true
  docker_container:
    name: api
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    restart_policy: on-failure
    pull: yes
    env:
      NODE_ENV: test
      GOOGLE_APPLICATION_CREDENTIALS: /etc/Teleport/gcp.json
    volumes:
      - "{{ config_directory_path }}/env.ini:{{ main_app_directory_path }}/.env"
      - "{{ config_directory_path }}/gcp.json:/etc/Teleport/gcp.json"
    ports:
      - 4000:4000