---
- name: Install nginx
  apt: name=nginx state=latest

- name: Check if dhparam.pem already exists.
  stat:
    path: /etc/nginx/ssl/dhparam.pem
  register: dhparam_already_generated

- name: Create the ssl directory
  file: path=/etc/nginx/ssl
    mode=0775
    state=directory
  when: not dhparam_already_generated.stat.exists

- name: Generate dhparam.pem
  shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  when: not dhparam_already_generated.stat.exists

- name: Copy the nginx conf file
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Create the config file directory
  file: path={{ config_directory_path }}
    mode=0775
    state=directory

- name: Copy the env file
  template: src=env.j2 dest={{ config_directory_path }}/env.ini

- name: Copy the gCloud credentials file
  template: src=gcloud.json.j2 dest={{ config_directory_path }}/gcp.json

- name: Copy the update contacts scores job script
  template: src=contacts-scores-job.sh.j2 dest=~/contacts-scores-job.sh

- name: Run api
  become: true
  docker_container:
    name: api
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    restart_policy: on-failure
    pull: yes
    env:
      NODE_ENV: "{{ node_env }}"
      GOOGLE_APPLICATION_CREDENTIALS: /etc/Teleport/gcp.json
    volumes:
      - "{{ config_directory_path }}/env.ini:{{ main_app_directory_path }}/.env"
      - "{{ config_directory_path }}/gcp.json:/etc/Teleport/gcp.json"
    ports:
      - 4000:4000

- name: Schedule update contact scores job
  cron:
    name: "Update contact scores"
    minute: "0"
    hour: "5"
    job: "sh ~/contacts-scores-job.sh > ~/contacts-scores-job.log 2>&1"

- name: restart nginx
  service:
    name: nginx
    state: restarted