---

#- name: ensure nginx is at the latest version
#  apt: name=nginx state=latest
#
#- name: Copy the nginx conf file
#  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf
#
#- name: start nginx
#  service:
#    name: nginx
#    state: started

- name: Run website
  become: true
  docker_container:
    name: website
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    restart_policy: on-failure
    pull: yes
    ports:
      - 8000:80

#- name: start nginx
#  service:
#    name: nginx
#    state: restarted