---

- name: Create the config file directory
  file: path={{ config_directory_path }}
    mode=0775
    state=directory

- name: Copy the env file
  template: src=env.j2 dest={{ config_directory_path }}/env.ini

- name: Run webapp
  become: true
  docker_container:
    name: webapp
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    restart_policy: on-failure
    pull: yes
    ports:
      - 3000:80
#      command: ./usr/share/nginx/html/env.sh && nginx -s quit && nginx -g "daemon off;"