---
version: "3.7"

services:
 website:
    build: "${PATH_TO_WEBSITE_FOLDER}"
    container_name: website
    ports:
      - 8000:8000
    volumes:
      - "${PATH_TO_WEBSITE_FOLDER}:/usr/src/app"
      - /usr/src/app/node_modules