---

#ssh
ansible_ssh_port: 22
ansible_user: ''
ansible_ssh_private_key_file: ~/.ssh/google_compute_engine

#Env variables
node_env: test

#database
db_base_url: 10.73.0.2
db_port: 27017
main_db_name: "{{ vault_main_db_name }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

#main server
main_server_port: 4000

#jwt
jwt_secret: "{{ vault_jwt_secret }}"
jwt_expiration: 720h

#agora
agora_app_id: "{{ vault_agora_app_id }}"
agora_app_certificate: "{{ vault_agora_app_certificate }}"

#opentalk
open_tok_api_key: "{{ vault_open_tok_api_key }}"
open_tok_api_secret: "{{ vault_open_tok_api_secret }}"

#redis
redis_port: 6379
redis_host: 10.0.0.3

#segment
segment_key: "{{ vault_segment_key }}"

#Sentry
sentry_dsn: "{{ vault_sentry_dsn }}"

#CORS
cors_webapp_origin: https://test-webapp.tlprt.io

#voxeet
voxeet_consumer_key: "{{ vault_voxeet_consumer_key }}"
voxeet_consumer_secret: "{{ voxeet_consumer_secret }}"

#BigQuery
bigquery_analytics_dataset_name: api_test_legacy

#docker
docker_image: eu.gcr.io/teleport-platform/api-legacy

#google cloud credentials
gcloud_credentials_type: "{{ vault_gcloud_credentials_type }}"
gcloud_credentials_project_id: "{{ vault_gcloud_credentials_project_id }}"
gcloud_credentials_private_key_id: "{{ vault_gcloud_credentials_private_key_id }}"
gcloud_credentials_private_key: "{{ vault_gcloud_credentials_private_key }}"
gcloud_credentials_client_email: "{{ vault_gcloud_credentials_client_email }}"
gcloud_credentials_client_id: "{{ vault_gcloud_credentials_client_id }}"
gcloud_credentials_auth_uri: "{{ vault_gcloud_credentials_auth_uri }}"
gcloud_credentials_token_uri: "{{ vault_gcloud_credentials_token_uri }}"
gcloud_credentials_auth_provider_x509_cert_url: "{{ vault_gcloud_credentials_auth_provider_x509_cert_url }}"
gcloud_credentials_client_x509_cert_url: "{{ vault_gcloud_credentials_client_x509_cert_url }}"

#cerftbot
certbot_domains:
  - test-api-legacy.tlprt.io

#nginx
nginx_api_server_name: test-api-legacy.tlprt.io